# -*- coding: utf-8 -*-
"""Drone de entrega.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14BNhc91rwfsB-z9cDdALBNsMQG4UoRo_

Os imports `random`, `time` e `clear_output` são usados para, respectivamente, gerar eventos aleatórios, controlar o intervalo de tempo da simulação e atualizar a saída visual no Google Colab sem acumular várias linhas na tela
"""

import random
import time
from IPython.display import clear_output

class Escritório:
  def __init__(self, largura=5, altura=5):
    self.largura = largura
    self.altura = altura
    self.base_recarga = (0, 0)
    self.maquina_cafe = (largura - 1, 0)
    self.mesa_cliente = (largura - 1, altura - 1)
    self.pedidos_pendentes = False


  def atualizar_pedidos(self):
    if not self.pedidos_pendentes:
      self.pedidos_pendentes = random.random() < 0.3

class RoboEntregador:
  def __init__(self, ambiente):
    self.pos = [0, 0]
    self.bateria = 100
    self.tem_cafe = False
    self.status = 'Aguardando...'
    self.ambiente = ambiente


  def mover_para(self, destino):
    dx = destino[0] - self.pos[0]
    dy = destino[1] - self.pos[1]

    if dx != 0:
        self.pos[0] += (dx > 0) - (dx < 0)
    elif dy != 0:
        self.pos[1] += (dy > 0) - (dy < 0)

    self.bateria -= 2


  def deliberar(self):
    x, y = self.pos

    if self.bateria < 20 and (x, y) != self.ambiente.base_recarga:
      self.status = 'Bateria baixa! Indo recarregar.'
      self.mover_para(self.ambiente.base_recarga)

    elif self.bateria < 20 and (x, y) == self.ambiente.base_recarga:
      self.status = 'Recarregando...'
      self.bateria = 100

    elif self.tem_cafe:
      if (x, y) == self.ambiente.mesa_cliente:
        self.status = 'Café entregue!'
        self.tem_cafe = False
        self.ambiente.pedidos_pendentes = False

      else:
        self.status = 'Entregando café.'
        self.mover_para(self.ambiente.mesa_cliente)

    elif self.ambiente.pedidos_pendentes:
      if (x, y) == self.ambiente.maquina_cafe:
          self.status = 'Coletando café na máquina...'
          self.tem_cafe = True

      else:
          self.status = 'Indo buscar café.'
          self.mover_para(self.ambiente.maquina_cafe)

    else:
      if (x, y) != self.ambiente.base_recarga:
          self.status = 'Sem pedidos. Voltando para base.'
          self.mover_para(self.ambiente.base_recarga)

      else:
          self.status = 'Em repouso...'

lugar = Escritório()
robo = RoboEntregador(lugar)

for turno in range(60):
  lugar.atualizar_pedidos()
  robo.deliberar()

  clear_output(wait=True)

  if lugar.pedidos_pendentes:
      status_pedido = "Sim"
  else:
      status_pedido = "Não"

  if robo.tem_cafe:
      status_cafe = "Sim"
  else:
      status_cafe = "Não"

  print(f"--- TURNO {turno+1} ---")
  print(f"Status do Robô: {robo.status}")
  print(f"Posição: {robo.pos} | Bateria: {robo.bateria}%")
  print(f"Pedido Pendente no Escritório: {status_pedido}")
  print(f"Carregando Café: {status_cafe}")

  for y in range(lugar.altura):
    linha = ""

    for x in range(lugar.largura):
      if [x, y] == robo.pos: linha += "🤖 "
      elif (x, y) == lugar.maquina_cafe: linha += "☕ "
      elif (x, y) == lugar.mesa_cliente: linha += "👤 "
      elif (x, y) == lugar.base_recarga: linha += "🔋 "
      else: linha += ".  "

    print(linha)
    time.sleep(0.4)